server:
  port: 7001
logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.apache.ibatis: DEBUG
spring:
  datasource:
      url: jdbc:mysql://47.100.219.248:3306/test?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

#      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: pb951028
#      driver-class-name: com.mysql.cj.jdbc.Driver





