version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /home/docker/zex-rpp/nginx/html:/usr/share/nginx/html
      - /home/docker/zex-rpp/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /home/docker/mysql/log:/var/log/mysql
      - /home/docker/mysql/data:/var/lib/mysql
      - /home/docker/mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test

  zex-rpp:
    image: zex-rpp:latest
    build: .
    ports:
      - 7001:7001
    depends_on:
      - mysql
